org: ferb7o2
app: sanangelmx-aws-nodejs-express-api
service: sanangelmx-aws-nodejs-express-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    MERCHANT_ID: ${param:MERCHANT_ID}
    CLOVER_API_KEY: ${param:CLOVER_API_KEY}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
