org: ferb7o2
app: sanangelmx-aws-nodejs-express-api
service: sanangelmx-aws-nodejs-express-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
